on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
    types: [opened, reopened, synchronize]
  workflow_call:
  workflow_dispatch:

name: ci-windowsl

env:
  DOTNET_VERSION: 8.0.x
  REGISTRY: ghcr.io

jobs:

  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Publish ShockOSC Windows
        run: dotnet publish ShockOsc/ShockOsc.csproj -c Release -f net8.0-windows10.0.19041.0 -o ./publish/ShockOsc

      - name: Upload ShockOSC Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ShockOsc
          path: publish/ShockOsc/*
          retention-days: 1
          if-no-files-found: error
  
  instller:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            Installer

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ShockOsc
          path: publish/


      - name: Create nsis installer
        uses: joncloud/makensis-action@publish
        with:
          script-file: ${{ github.workspace }}/Installer/installer.nsi
          additional-plugin-paths: ${{ github.workspace }}/Installer/Plugins
          
      - name: Upload ShockOSC Windows Setup
        uses: actions/upload-artifact@v4
        with:
          name: ShockOsc_Setup
          path: Installer/ShockOsc_Setup.exe
          retention-days: 7
          if-no-files-found: error